# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ce29IffOYCKCu0sxdC9a8mIXvyxeqyML
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

# Sample data (dummy for now)
data = {
    "study_hours": [2, 4, 6, 8],
    "marks": [50, 60, 70, 85]
}
df = pd.DataFrame(data)

X = df[["study_hours"]]
y = df["marks"]

model = LinearRegression()
model.fit(X, y)

prediction = model.predict([[5]])
print("Predicted Marks:", prediction[0])