# -*- coding: utf-8 -*-
"""Smart_Study_Planner_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UGLq8cBFyK7yY2XmgzPxNh6rFQy6xzR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("student_data.csv")
df.head()

print("Rows and Columns:", df.shape)
print(df.describe())

df.columns

df.drop(columns=['Timestamp', 'Full Name'], axis=1, inplace=True)
df.columns

df.info()
df.isnull().sum()

# First, strip whitespace from column names to ensure correct access
df.columns = df.columns.str.strip()

# Fill missing values in 'Daily Social Media Usage' with the mode
df['Daily Social Media Usage'].fillna(df['Daily Social Media Usage'].mode()[0], inplace=True)

study_map = {
    "Less than 2 hours":1,
    "2–4 hours":2,
    "4–6 hours":3,
    "More than 6 hours":4
}

df.columns = df.columns.str.strip()
df["Average Study Hours per Day"] = df["Average Study Hours per Day"].astype(str).str.replace('-', '–').map(study_map)

attendance_map = {
    "Below 60%":1,
    "60–75%":2,
    "75–90%":3,
    "Above 90%":4
}

df["Attendance Percentage"] = df["Attendance Percentage"].astype(str).str.replace('-', '–').map(attendance_map)

score_map = {
    "Below 50%":1,
    "50–60%":2,
    "60–75%":3,
    "75–90%":4,
    "Above 90%":5
}

df["Previous Exam Percentage"] = df["Previous Exam Percentage"].astype(str).str.replace('-', '–').map(score_map)

# Handle '75-90' by replacing it with '75-90%' before standardizing dash and mapping
df['What was your percentage in your most recent exam?'] = df['What was your percentage in your most recent exam?'].astype(str).replace('75-90', '75-90%')
df["What was your percentage in your most recent exam?"] = df["What was your percentage in your most recent exam?"].str.replace('-', '–').map(score_map)

sleep_map = {
    "Less than 5 hours":1,
    "5–6 hours":2,
    "6–8 hours":3,
    "More than 8 hours":4
}

df["Average Sleep Hours per Day"] = df["Average Sleep Hours per Day"].astype(str).str.replace('-', '–').map(sleep_map)

social_map = {
    "Less than 1 hour":1,
    "1–3 hours":2,
    "3–5 hours":3,
    "More than 5 hours":4
}

df["Daily Social Media Usage"] = df["Daily Social Media Usage"].astype(str).str.replace('-', '–').map(social_map)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])
df["Year"] = le.fit_transform(df["Year"])
df["Do you feel stressed during exams?"] = le.fit_transform(df["Do you feel stressed during exams?"])
df["How would you rate subject difficulty?"] = le.fit_transform(df["How would you rate subject difficulty?"])

X = df.drop("What was your percentage in your most recent exam?", axis=1)
y = df["What was your percentage in your most recent exam?"]

sns.countplot(x=y)
plt.title("Exam Score Distribution")
plt.show()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

def study_plan(score):
    if score <= 2:
        return "Study 3 hrs/day, reduce distractions, revise basics"
    elif score == 3:
        return "Study 2.5 hrs/day, solve tests regularly"
    else:
        return "Maintain consistency and revise smartly"

model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

pred = model.predict(X_test)

acc = accuracy_score(y_test, pred) * 100
print("Model Accuracy: {:.2f}%".format(acc))

print(classification_report(y_test, pred))

cm = confusion_matrix(y_test, pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)
print(importance)

score_label = {
    1:"Below 50%",
    2:"50-60%",
    3:"60-75%",
    4:"75-90%",
    5:"Above 90%"
}

sample = X.iloc[[0]]
result = model.predict(sample)[0]

print("Predicted Score:", score_label[int(result)])
print("Plan:", study_plan(result))
print("The project successfully predicts student performance and provides personalized study recommendations.")